### ISSUE TITLE
lib:build failed

### ISSUE THREAD

**Issue by Ofiraf** [shlomiassaf/angular-library-starter#13]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
On windows OS there is error message when running lib:build
"stderr: 'rm' is not recognized as an internal or external command"

* **What is the current behavior?**
Build failing on windows OS

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

Support for Windows CLI

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 4.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by shlomiassaf** [comment]
fixed via [862f6ea](https://github.com/shlomiassaf/angular-library-starter/commit/862f6ea4c1de0bf2b87824d74a9c34e706eed7b3)
