### ISSUE TITLE
Angular 5 Support

### ISSUE THREAD

**Issue by Crazyht** [shlomiassaf/angular-library-starter#20]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

Need to migrate to Angular 5

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

Support new version

* **Please tell us about your environment:**

- Angular version: 5.0.0
- Browser: all 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

If I try to update all packages, I take compilation Error "Must specify "tsConfigPath" in the configuration of @ngtools/webpack.". How I can resolve this ? 

Ohter question is : when project is migrated, resulting library continue can be used in Ng4 project or I need to maintain two version ?

**Comment by shlomiassaf** [comment]
integration done in PR ##22
