### ISSUE TITLE
@scope/my-lib/index is imported by....but could not be resolved – treating it as an external dependency

### ISSUE THREAD

**Issue by jogelin** [shlomiassaf/angular-library-starter#7]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
If I have 2 library on the second one is depending of the first one, I get this error/warning: 
```
[13:06:41] Finished '!build:webpack' after 9 s
[13:06:41] Starting '!build:rollup:fesm'...
'@scope/common/index' is imported by dist_package\@scope\notification-management\src\notification.model.js, but could not be resolved – treating it as an external dependency
[13:06:41] Finished '!build:rollup:fesm' after 43 ms
[13:06:41] Starting '!build:fesm:es5'...
'@scope/common/index' is imported by dist_package\@scope\notification-management\src\notification.model.js, but could not be resolved – treating it as an external dependency
[13:06:41] Finished '!build:fesm:es5' after 26 ms
[13:06:41] Starting '!build:rollup:umd'...
'@scope/common/index' is imported by dist_package\@scope\notification-management\bundle\notification-management.es5.js, but could not be resolved – treating it as an external dependency
No name was provided for external module '@scope/common/index' in options.globals – guessing '_scope_common_index'
[13:06:41] Finished '!build:rollup:umd' after 43 ms
[13:06:41] Starting '!minifyAndGzip'...
```
But I added in my rollup configuration:
```
const globals = {
...
    '@scope/common': 'sxpbelux.common',
...
}
```

* **What is the expected behavior?**
To not have this warning. I am not an expert but why the `/index` is added to my lib ?

**Comment by shlomiassaf** [comment]
The `/index` is added to your code by the angular compiler, more accurately `tsickle` which is used by the angular compiler.

This is a known bug, see the [examples](https://github.com/shlomiassaf/angular-library-starter/tree/master/examples) pages, at the end of the page there is a comment about that.

The solution is not using an `index.ts` files as your entry point.

In that page you'll see examples of how to achieve that

**Comment by jogelin** [comment]
It works, thank you ! I didn't see your comment...

Just to summarize: 

- Rename your src/index.ts -> src/my-lib.ts
- Add in your package.json:
```
{
  "description": "my-lib",
  "libConfig": {
    "entry": "my-lib"
  },
```
